spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/sda_j113_spring?serverTimezone=Europe/Warsaw&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      # liquibase / flyway
      ddl-auto: update
#    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

application:
  default:
    roles:
      - ROLE_ADMIN
      - ROLE_USER
      - ROLE_MODERATOR
    users:
      - username: admin
        password: nimda
        roles: ROLE_ADMIN,ROLE_USER,ROLE_MODERATOR
      - username: user
        password: user
        roles: ROLE_USER